%% ========================================================================
% Step 9.10: Tip-Error and Shape-Error Distribution Curves
% ========================================================================
rng('default');
disp('--------------------------------------------------');
disp('9.10 Generating tip-error and shape-error distribution curves...');
tip_error_plot = error_prop_plot;
export_this_figure = false;
output_folder = 'IEEE_Error_Distribution_Curves';

if ~exist(output_folder, 'dir')
    mkdir(output_folder);
end

font_name = 'Times New Roman';

% =========================================================================
% 1. Required data
% =========================================================================

if ~exist('tip_error_plot', 'var')
    error('Missing tip_error_plot.');
end

if ~exist('shape_error_plot', 'var')
    error('Missing shape_error_plot.');
end

tip_error_plot = tip_error_plot(:);
shape_error_plot = shape_error_plot(:);

tip_error_plot = tip_error_plot(isfinite(tip_error_plot));
shape_error_plot = shape_error_plot(isfinite(shape_error_plot));

% =========================================================================
% 2. Bin settings
% =========================================================================

tip_bin_width = 0.20;      % mm
shape_bin_width = 0.10;    % mm

% =========================================================================
% 3. Tip-error counts
% =========================================================================

tip_min = min(tip_error_plot);
tip_max = max(tip_error_plot);

tip_first_edge = floor(tip_min / tip_bin_width) * tip_bin_width;
tip_last_edge  = ceil(tip_max / tip_bin_width) * tip_bin_width;

tip_edges = tip_first_edge:tip_bin_width:tip_last_edge;

if tip_edges(end) <= tip_max
    tip_edges(end+1) = tip_edges(end) + tip_bin_width;
end

tip_counts = histcounts(tip_error_plot, tip_edges);
tip_centers = tip_edges(1:end-1) + diff(tip_edges)/2;

mean_tip_error = mean(tip_error_plot);

% =========================================================================
% 4. Shape-error counts
% =========================================================================

shape_min = min(shape_error_plot);
shape_max = max(shape_error_plot);

shape_first_edge = floor(shape_min / shape_bin_width) * shape_bin_width;
shape_last_edge  = ceil(shape_max / shape_bin_width) * shape_bin_width;

shape_edges = shape_first_edge:shape_bin_width:shape_last_edge;

if shape_edges(end) <= shape_max
    shape_edges(end+1) = shape_edges(end) + shape_bin_width;
end

shape_counts = histcounts(shape_error_plot, shape_edges);
shape_centers = shape_edges(1:end-1) + diff(shape_edges)/2;

mean_shape_error = mean(shape_error_plot);

% =========================================================================
% 5. Colors
% =========================================================================

c_tip = [0, 158, 115] / 255;
c_shape = [0, 114, 189] / 255;
c_mean = [1, 0, 0];

% =========================================================================
% 6. Tip-error distribution curve
% =========================================================================

fig_tip = figure( ...
    'Name', 'Tip Error Distribution Curve', ...
    'Color', 'w', ...
    'Units', 'pixels', ...
    'Position', [120, 120, 850, 600]);

ax_tip = axes(fig_tip);
hold(ax_tip, 'on');

plot( ...
    ax_tip, ...
    tip_centers, ...
    tip_counts, ...
    '-o', ...
    'Color', c_tip, ...
    'LineWidth', 2.8, ...
    'MarkerSize', 7, ...
    'MarkerFaceColor', 'w', ...
    'MarkerEdgeColor', c_tip);

xline( ...
    ax_tip, ...
    mean_tip_error, ...
    '--', ...
    sprintf('Mean: %.2f mm', mean_tip_error), ...
    'Color', c_mean, ...
    'LineWidth', 2.5, ...
    'FontName', font_name, ...
    'FontSize', 18, ...
    'LabelOrientation', 'aligned', ...
    'LabelVerticalAlignment', 'middle');

xlabel( ...
    ax_tip, ...
    'Tip Error (mm)', ...
    'FontName', font_name, ...
    'FontSize', 26, ...
    'FontWeight', 'bold');

ylabel( ...
    ax_tip, ...
    'Error Count', ...
    'FontName', font_name, ...
    'FontSize', 26, ...
    'FontWeight', 'bold');

set( ...
    ax_tip, ...
    'FontName', font_name, ...
    'FontSize', 22, ...
    'LineWidth', 1.5, ...
    'TickDir', 'in', ...
    'Box', 'on', ...
    'XMinorTick', 'on', ...
    'YMinorTick', 'on');

grid(ax_tip, 'on');
grid(ax_tip, 'minor');

ax_tip.GridAlpha = 0.18;
ax_tip.MinorGridAlpha = 0.07;

xlim(ax_tip, [tip_edges(1), tip_edges(end)]);

tip_max_count = max(tip_counts);
tip_y_upper = max(1, ceil(tip_max_count / 2) * 2);

ylim(ax_tip, [0, tip_y_upper]);
yticks(ax_tip, 0:2:tip_y_upper);

title(ax_tip, '');

if export_this_figure
    exportgraphics( ...
        fig_tip, ...
        fullfile(output_folder, 'Tip_Error_Distribution_Curve.pdf'), ...
        'ContentType', 'vector');

    exportgraphics( ...
        fig_tip, ...
        fullfile(output_folder, 'Tip_Error_Distribution_Curve.png'), ...
        'Resolution', 600);

    savefig( ...
        fig_tip, ...
        fullfile(output_folder, 'Tip_Error_Distribution_Curve.fig'));
end

% =========================================================================
% 7. Shape-error distribution curve
% =========================================================================

fig_shape = figure( ...
    'Name', 'Shape Error Distribution Curve', ...
    'Color', 'w', ...
    'Units', 'pixels', ...
    'Position', [120, 120, 850, 600]);

ax_shape = axes(fig_shape);
hold(ax_shape, 'on');

plot( ...
    ax_shape, ...
    shape_centers, ...
    shape_counts, ...
    '-o', ...
    'Color', c_shape, ...
    'LineWidth', 2.8, ...
    'MarkerSize', 7, ...
    'MarkerFaceColor', 'w', ...
    'MarkerEdgeColor', c_shape);

xline( ...
    ax_shape, ...
    mean_shape_error, ...
    '--', ...
    sprintf('Mean: %.2f mm', mean_shape_error), ...
    'Color', c_mean, ...
    'LineWidth', 2.5, ...
    'FontName', font_name, ...
    'FontSize', 18, ...
    'LabelOrientation', 'aligned', ...
    'LabelVerticalAlignment', 'middle');

xlabel( ...
    ax_shape, ...
    'Shape Error (mm)', ...
    'FontName', font_name, ...
    'FontSize', 26, ...
    'FontWeight', 'bold');

ylabel( ...
    ax_shape, ...
    'Error Count', ...
    'FontName', font_name, ...
    'FontSize', 26, ...
    'FontWeight', 'bold');

set( ...
    ax_shape, ...
    'FontName', font_name, ...
    'FontSize', 22, ...
    'LineWidth', 1.5, ...
    'TickDir', 'in', ...
    'Box', 'on', ...
    'XMinorTick', 'on', ...
    'YMinorTick', 'on');

grid(ax_shape, 'on');
grid(ax_shape, 'minor');

ax_shape.GridAlpha = 0.18;
ax_shape.MinorGridAlpha = 0.07;

xlim(ax_shape, [shape_edges(1), shape_edges(end)]);

shape_max_count = max(shape_counts);
shape_y_upper = max(1, ceil(shape_max_count / 2) * 2);

ylim(ax_shape, [0, shape_y_upper]);
yticks(ax_shape, 0:2:shape_y_upper);

title(ax_shape, '');

if export_this_figure
    exportgraphics( ...
        fig_shape, ...
        fullfile(output_folder, 'Shape_Error_Distribution_Curve.pdf'), ...
        'ContentType', 'vector');

    exportgraphics( ...
        fig_shape, ...
        fullfile(output_folder, 'Shape_Error_Distribution_Curve.png'), ...
        'Resolution', 600);

    savefig( ...
        fig_shape, ...
        fullfile(output_folder, 'Shape_Error_Distribution_Curve.fig'));
end

% =========================================================================
% 8. Report
% =========================================================================

fprintf('\n================ Error Distribution Summary ================\n');
fprintf('Tip-error samples        : %d\n', numel(tip_error_plot));
fprintf('Mean tip error           : %.4f mm\n', mean_tip_error);
fprintf('Shape-error samples      : %d\n', numel(shape_error_plot));
fprintf('Mean shape error         : %.4f mm\n', mean_shape_error);
fprintf('Tip histogram count sum  : %d\n', sum(tip_counts));
fprintf('Shape histogram count sum: %d\n', sum(shape_counts));
fprintf('============================================================\n');

disp('>>> Tip and shape error distribution curves generated.');